### ISSUE TITLE
What was the reason for switching from Rust to Python?

### ISSUE THREAD

**Issue by wh5a** [QCGPU/qcgpu#5]
I was looking for Rust implementation of quantum computer simulators but found you switched to Python. Could you share the reasons? Thank you!

**Comment by adamisntdead** [comment]
Hello!

The main reason for the rewrite was integration with other python libraries such as Qiskit.
The code is mainly OpenCL anyway, so there was no real reason to use rust, and python gave me some more flexibility.

Any other questions just ask!

**Comment by KyGost** [comment]
The [website](https://qcgpu.github.io/) is out of date and had me quite lost, perhaps it could be updated?

As an aside-- frankly I was hopeful for the rust implementation but was disappointed to see this. Realistically, I shouldn't be-- it is just a language.
