### ISSUE TITLE
Error when installing.

### ISSUE THREAD

**Issue by conorcaseyc** [QCGPU/qcgpu#6]
When I attempt to download the package via pip, it fails. The error code I received is included below.

Collecting qcgpu
  Using cached https://files.pythonhosted.org/packages/b6/fa/170edf5e1a17e9d6f981cdf8c9c0aec278562e3b4d8db2f82dbe541e416e/qcgpu-0.1.0-py3-none-any.whl
Requirement already satisfied: numpy in ./anaconda3/lib/python3.7/site-packages (from qcgpu) (1.15.4)
Requirement already satisfied: mako in ./anaconda3/lib/python3.7/site-packages (from qcgpu) (1.0.7)
Collecting pyopencl (from qcgpu)
  Using cached https://files.pythonhosted.org/packages/bc/58/3ab1246e94986f1b6953e76d7ea7e69d2dbfef7b3f3874eded48524a024f/pyopencl-2018.2.2.tar.gz
Requirement already satisfied: pybind11 in ./anaconda3/lib/python3.7/site-packages (from qcgpu) (2.2.4)
Requirement already satisfied: MarkupSafe>=0.9.2 in ./anaconda3/lib/python3.7/site-packages (from mako->qcgpu) (1.0)
Requirement already satisfied: pytools>=2017.6 in ./anaconda3/lib/python3.7/site-packages (from pyopencl->qcgpu) (2018.5.2)
Requirement already satisfied: decorator>=3.2.0 in ./anaconda3/lib/python3.7/site-packages (from pyopencl->qcgpu) (4.3.0)
Requirement already satisfied: appdirs>=1.4.0 in ./anaconda3/lib/python3.7/site-packages (from pyopencl->qcgpu) (1.4.3)
Requirement already satisfied: six>=1.9.0 in ./anaconda3/lib/python3.7/site-packages (from pyopencl->qcgpu) (1.11.0)
Building wheels for collected packages: pyopencl
  Running setup.py bdist_wheel for pyopencl ... error
  Complete output from command /home/conor/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-wf8xbysy/pyopencl/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-misiq730 --python-tag cp37:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.7
  creating build/lib.linux-x86_64-3.7/pyopencl
  copying pyopencl/__init__.py -> build/lib.linux-x86_64-3.7/pyopencl
  copying pyopencl/cltypes.py -> build/lib.linux-x86_64-3.7/pyopencl
  copying pyopencl/reduction.py -> build/lib.linux-x86_64-3.7/pyopencl
  copying pyopencl/bitonic_sort.py -> build/lib.linux-x86_64-3.7/pyopencl
  copying pyopencl/_cluda.py -> build/lib.linux-x86_64-3.7/pyopencl
  copying pyopencl/bitonic_sort_templates.py -> build/lib.linux-x86_64-3.7/pyopencl
  copying pyopencl/elementwise.py -> build/lib.linux-x86_64-3.7/pyopencl
  copying pyopencl/capture_call.py -> build/lib.linux-x86_64-3.7/pyopencl
  copying pyopencl/clrandom.py -> build/lib.linux-x86_64-3.7/pyopencl
  copying pyopencl/tools.py -> build/lib.linux-x86_64-3.7/pyopencl
  copying pyopencl/algorithm.py -> build/lib.linux-x86_64-3.7/pyopencl
  copying pyopencl/_mymako.py -> build/lib.linux-x86_64-3.7/pyopencl
  copying pyopencl/scan.py -> build/lib.linux-x86_64-3.7/pyopencl
  copying pyopencl/_buffers.py -> build/lib.linux-x86_64-3.7/pyopencl
  copying pyopencl/ipython_ext.py -> build/lib.linux-x86_64-3.7/pyopencl
  copying pyopencl/clmath.py -> build/lib.linux-x86_64-3.7/pyopencl
  copying pyopencl/cache.py -> build/lib.linux-x86_64-3.7/pyopencl
  copying pyopencl/version.py -> build/lib.linux-x86_64-3.7/pyopencl
  copying pyopencl/invoker.py -> build/lib.linux-x86_64-3.7/pyopencl
  copying pyopencl/array.py -> build/lib.linux-x86_64-3.7/pyopencl
  creating build/lib.linux-x86_64-3.7/pyopencl/characterize
  copying pyopencl/characterize/__init__.py -> build/lib.linux-x86_64-3.7/pyopencl/characterize
  copying pyopencl/characterize/performance.py -> build/lib.linux-x86_64-3.7/pyopencl/characterize
  creating build/lib.linux-x86_64-3.7/pyopencl/compyte
  copying pyopencl/compyte/__init__.py -> build/lib.linux-x86_64-3.7/pyopencl/compyte
  copying pyopencl/compyte/dtypes.py -> build/lib.linux-x86_64-3.7/pyopencl/compyte
  copying pyopencl/compyte/array.py -> build/lib.linux-x86_64-3.7/pyopencl/compyte
  creating build/lib.linux-x86_64-3.7/pyopencl/compyte/ndarray
  copying pyopencl/compyte/ndarray/__init__.py -> build/lib.linux-x86_64-3.7/pyopencl/compyte/ndarray
  copying pyopencl/compyte/ndarray/setup_opencl.py -> build/lib.linux-x86_64-3.7/pyopencl/compyte/ndarray
  copying pyopencl/compyte/ndarray/test_gpu_ndarray.py -> build/lib.linux-x86_64-3.7/pyopencl/compyte/ndarray
  copying pyopencl/compyte/ndarray/gen_elemwise.py -> build/lib.linux-x86_64-3.7/pyopencl/compyte/ndarray
  copying pyopencl/compyte/ndarray/gen_reduction.py -> build/lib.linux-x86_64-3.7/pyopencl/compyte/ndarray
  copying pyopencl/compyte/ndarray/test_gpu_elemwise.py -> build/lib.linux-x86_64-3.7/pyopencl/compyte/ndarray
  running egg_info
  writing pyopencl.egg-info/PKG-INFO
  writing dependency_links to pyopencl.egg-info/dependency_links.txt
  writing requirements to pyopencl.egg-info/requires.txt
  writing top-level names to pyopencl.egg-info/top_level.txt
  reading manifest file 'pyopencl.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no files found matching '*.h'
  warning: no files found matching 'doc/_static/*.css'
  warning: no files found matching 'doc/_templates/*.html'
  warning: no files found matching '*.py.in'
  writing manifest file 'pyopencl.egg-info/SOURCES.txt'
  creating build/lib.linux-x86_64-3.7/pyopencl/cl
  copying pyopencl/cl/pyopencl-airy.cl -> build/lib.linux-x86_64-3.7/pyopencl/cl
  copying pyopencl/cl/pyopencl-bessel-j-complex.cl -> build/lib.linux-x86_64-3.7/pyopencl/cl
  copying pyopencl/cl/pyopencl-bessel-j.cl -> build/lib.linux-x86_64-3.7/pyopencl/cl
  copying pyopencl/cl/pyopencl-bessel-y.cl -> build/lib.linux-x86_64-3.7/pyopencl/cl
  copying pyopencl/cl/pyopencl-complex.h -> build/lib.linux-x86_64-3.7/pyopencl/cl
  copying pyopencl/cl/pyopencl-eval-tbl.cl -> build/lib.linux-x86_64-3.7/pyopencl/cl
  copying pyopencl/cl/pyopencl-hankel-complex.cl -> build/lib.linux-x86_64-3.7/pyopencl/cl
  copying pyopencl/cl/pyopencl-ranluxcl.cl -> build/lib.linux-x86_64-3.7/pyopencl/cl
  creating build/lib.linux-x86_64-3.7/pyopencl/cl/pyopencl-random123
  copying pyopencl/cl/pyopencl-random123/array.h -> build/lib.linux-x86_64-3.7/pyopencl/cl/pyopencl-random123
  copying pyopencl/cl/pyopencl-random123/openclfeatures.h -> build/lib.linux-x86_64-3.7/pyopencl/cl/pyopencl-random123
  copying pyopencl/cl/pyopencl-random123/philox.cl -> build/lib.linux-x86_64-3.7/pyopencl/cl/pyopencl-random123
  copying pyopencl/cl/pyopencl-random123/threefry.cl -> build/lib.linux-x86_64-3.7/pyopencl/cl/pyopencl-random123
  running build_ext
  creating tmp
  gcc -pthread -B /home/conor/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -fwrapv -Wall -O3 -DNDEBUG -fPIC -I/home/conor/anaconda3/include/python3.7m -c /tmp/tmp5e430x_u.cpp -o tmp/tmp5e430x_u.o -std=c++14
  gcc -pthread -B /home/conor/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -fwrapv -Wall -O3 -DNDEBUG -fPIC -I/home/conor/anaconda3/include/python3.7m -c /tmp/tmpaohswv3o.cpp -o tmp/tmpaohswv3o.o -fvisibility=hidden
  building 'pyopencl._cl' extension
  creating build/temp.linux-x86_64-3.7
  creating build/temp.linux-x86_64-3.7/src
  gcc -pthread -B /home/conor/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -fwrapv -Wall -O3 -DNDEBUG -fPIC -DPYGPU_PACKAGE=pyopencl -DPYGPU_PYOPENCL=1 -Ipybind11/include -I/home/conor/anaconda3/include/python3.7m -I/home/conor/.local/include/python3.7m -I/home/conor/anaconda3/lib/python3.7/site-packages/numpy/core/include -I/home/conor/anaconda3/lib/python3.7/site-packages/numpy/core/include -I/home/conor/anaconda3/lib/python3.7/site-packages/numpy/core/include -I/home/conor/anaconda3/include/python3.7m -c src/wrap_constants.cpp -o build/temp.linux-x86_64-3.7/src/wrap_constants.o -fvisibility=hidden -DVERSION_INFO="2018.2.2" -std=c++14 -fvisibility=hidden
  In file included from src/wrap_constants.cpp:27:0:
  src/wrap_cl.hpp:57:10: fatal error: CL/cl.h: No such file or directory
   #include <CL/cl.h>
            ^~~~~~~~~
  compilation terminated.
  error: command 'gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for pyopencl
  Running setup.py clean for pyopencl
Failed to build pyopencl
Installing collected packages: pyopencl, qcgpu
  Running setup.py install for pyopencl ... error
    Complete output from command /home/conor/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-wf8xbysy/pyopencl/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-v1hz2q9c/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.7
    creating build/lib.linux-x86_64-3.7/pyopencl
    copying pyopencl/__init__.py -> build/lib.linux-x86_64-3.7/pyopencl
    copying pyopencl/cltypes.py -> build/lib.linux-x86_64-3.7/pyopencl
    copying pyopencl/reduction.py -> build/lib.linux-x86_64-3.7/pyopencl
    copying pyopencl/bitonic_sort.py -> build/lib.linux-x86_64-3.7/pyopencl
    copying pyopencl/_cluda.py -> build/lib.linux-x86_64-3.7/pyopencl
    copying pyopencl/bitonic_sort_templates.py -> build/lib.linux-x86_64-3.7/pyopencl
    copying pyopencl/elementwise.py -> build/lib.linux-x86_64-3.7/pyopencl
    copying pyopencl/capture_call.py -> build/lib.linux-x86_64-3.7/pyopencl
    copying pyopencl/clrandom.py -> build/lib.linux-x86_64-3.7/pyopencl
    copying pyopencl/tools.py -> build/lib.linux-x86_64-3.7/pyopencl
    copying pyopencl/algorithm.py -> build/lib.linux-x86_64-3.7/pyopencl
    copying pyopencl/_mymako.py -> build/lib.linux-x86_64-3.7/pyopencl
    copying pyopencl/scan.py -> build/lib.linux-x86_64-3.7/pyopencl
    copying pyopencl/_buffers.py -> build/lib.linux-x86_64-3.7/pyopencl
    copying pyopencl/ipython_ext.py -> build/lib.linux-x86_64-3.7/pyopencl
    copying pyopencl/clmath.py -> build/lib.linux-x86_64-3.7/pyopencl
    copying pyopencl/cache.py -> build/lib.linux-x86_64-3.7/pyopencl
    copying pyopencl/version.py -> build/lib.linux-x86_64-3.7/pyopencl
    copying pyopencl/invoker.py -> build/lib.linux-x86_64-3.7/pyopencl
    copying pyopencl/array.py -> build/lib.linux-x86_64-3.7/pyopencl
    creating build/lib.linux-x86_64-3.7/pyopencl/characterize
    copying pyopencl/characterize/__init__.py -> build/lib.linux-x86_64-3.7/pyopencl/characterize
    copying pyopencl/characterize/performance.py -> build/lib.linux-x86_64-3.7/pyopencl/characterize
    creating build/lib.linux-x86_64-3.7/pyopencl/compyte
    copying pyopencl/compyte/__init__.py -> build/lib.linux-x86_64-3.7/pyopencl/compyte
    copying pyopencl/compyte/dtypes.py -> build/lib.linux-x86_64-3.7/pyopencl/compyte
    copying pyopencl/compyte/array.py -> build/lib.linux-x86_64-3.7/pyopencl/compyte
    creating build/lib.linux-x86_64-3.7/pyopencl/compyte/ndarray
    copying pyopencl/compyte/ndarray/__init__.py -> build/lib.linux-x86_64-3.7/pyopencl/compyte/ndarray
    copying pyopencl/compyte/ndarray/setup_opencl.py -> build/lib.linux-x86_64-3.7/pyopencl/compyte/ndarray
    copying pyopencl/compyte/ndarray/test_gpu_ndarray.py -> build/lib.linux-x86_64-3.7/pyopencl/compyte/ndarray
    copying pyopencl/compyte/ndarray/gen_elemwise.py -> build/lib.linux-x86_64-3.7/pyopencl/compyte/ndarray
    copying pyopencl/compyte/ndarray/gen_reduction.py -> build/lib.linux-x86_64-3.7/pyopencl/compyte/ndarray
    copying pyopencl/compyte/ndarray/test_gpu_elemwise.py -> build/lib.linux-x86_64-3.7/pyopencl/compyte/ndarray
    running egg_info
    writing pyopencl.egg-info/PKG-INFO
    writing dependency_links to pyopencl.egg-info/dependency_links.txt
    writing requirements to pyopencl.egg-info/requires.txt
    writing top-level names to pyopencl.egg-info/top_level.txt
    reading manifest file 'pyopencl.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching '*.h'
    warning: no files found matching 'doc/_static/*.css'
    warning: no files found matching 'doc/_templates/*.html'
    warning: no files found matching '*.py.in'
    writing manifest file 'pyopencl.egg-info/SOURCES.txt'
    creating build/lib.linux-x86_64-3.7/pyopencl/cl
    copying pyopencl/cl/pyopencl-airy.cl -> build/lib.linux-x86_64-3.7/pyopencl/cl
    copying pyopencl/cl/pyopencl-bessel-j-complex.cl -> build/lib.linux-x86_64-3.7/pyopencl/cl
    copying pyopencl/cl/pyopencl-bessel-j.cl -> build/lib.linux-x86_64-3.7/pyopencl/cl
    copying pyopencl/cl/pyopencl-bessel-y.cl -> build/lib.linux-x86_64-3.7/pyopencl/cl
    copying pyopencl/cl/pyopencl-complex.h -> build/lib.linux-x86_64-3.7/pyopencl/cl
    copying pyopencl/cl/pyopencl-eval-tbl.cl -> build/lib.linux-x86_64-3.7/pyopencl/cl
    copying pyopencl/cl/pyopencl-hankel-complex.cl -> build/lib.linux-x86_64-3.7/pyopencl/cl
    copying pyopencl/cl/pyopencl-ranluxcl.cl -> build/lib.linux-x86_64-3.7/pyopencl/cl
    creating build/lib.linux-x86_64-3.7/pyopencl/cl/pyopencl-random123
    copying pyopencl/cl/pyopencl-random123/array.h -> build/lib.linux-x86_64-3.7/pyopencl/cl/pyopencl-random123
    copying pyopencl/cl/pyopencl-random123/openclfeatures.h -> build/lib.linux-x86_64-3.7/pyopencl/cl/pyopencl-random123
    copying pyopencl/cl/pyopencl-random123/philox.cl -> build/lib.linux-x86_64-3.7/pyopencl/cl/pyopencl-random123
    copying pyopencl/cl/pyopencl-random123/threefry.cl -> build/lib.linux-x86_64-3.7/pyopencl/cl/pyopencl-random123
    running build_ext
    gcc -pthread -B /home/conor/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -fwrapv -Wall -O3 -DNDEBUG -fPIC -I/home/conor/anaconda3/include/python3.7m -c /tmp/tmp_uneib6t.cpp -o tmp/tmp_uneib6t.o -std=c++14
    gcc -pthread -B /home/conor/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -fwrapv -Wall -O3 -DNDEBUG -fPIC -I/home/conor/anaconda3/include/python3.7m -c /tmp/tmp3aeuupkf.cpp -o tmp/tmp3aeuupkf.o -fvisibility=hidden
    building 'pyopencl._cl' extension
    creating build/temp.linux-x86_64-3.7
    creating build/temp.linux-x86_64-3.7/src
    gcc -pthread -B /home/conor/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -fwrapv -Wall -O3 -DNDEBUG -fPIC -DPYGPU_PACKAGE=pyopencl -DPYGPU_PYOPENCL=1 -Ipybind11/include -I/home/conor/anaconda3/include/python3.7m -I/home/conor/.local/include/python3.7m -I/home/conor/anaconda3/lib/python3.7/site-packages/numpy/core/include -I/home/conor/anaconda3/lib/python3.7/site-packages/numpy/core/include -I/home/conor/anaconda3/lib/python3.7/site-packages/numpy/core/include -I/home/conor/anaconda3/include/python3.7m -c src/wrap_constants.cpp -o build/temp.linux-x86_64-3.7/src/wrap_constants.o -fvisibility=hidden -DVERSION_INFO="2018.2.2" -std=c++14 -fvisibility=hidden
    In file included from src/wrap_constants.cpp:27:0:
    src/wrap_cl.hpp:57:10: fatal error: CL/cl.h: No such file or directory
     #include <CL/cl.h>
              ^~~~~~~~~
    compilation terminated.
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/home/conor/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-wf8xbysy/pyopencl/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-v1hz2q9c/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-wf8xbysy/pyopencl/

**Comment by adamisntdead** [comment]
Looking up some stuff, to install pyopencl using anadonda, you may need to run:

```bash
$ conda install pyopencl
```

Also, if you don't have a dedicated GPU and don't have OpenCL drivers for your CPU, you can go and install [pocl](http://portablecl.org/)
with the command 

```bash
$ conda install pocl
```

**Comment by conorcaseyc** [comment]
Installing both modules separately fixed the issue, thank you.

**Comment by adamisntdead** [comment]
I will update the README to match, the dependencies are always a bit of an issue.
If you want to see how to do some more interesting stuff with it, you can DM me on twitter (@adamisntdead) or email me.
